### PR TITLE
Add support for 64 bit VS 2022

### LINKED ISSUE #72: Add support for VS 2022
🙏

Thanks!

### PR DESCRIPTION
**Pull request by kzu**
Basically copied from https://github.com/madskristensen/OpenCommandLine/commit/595633f4b4fa541a1fb44a683fd69443d2a63dbe

Fixes #72

### CODE REVIEW

**Comment by kzu** [comment]
Build issue seems to be the same as the tip of master, so, likely unrelated to this change

**Comment by pharring** [comment]
Thanks for the PR. Support for VS 2022 is going to involve a bit more than this, though. I want to maintain a VS 2019 build and VSIX -- Mads has a shared project model that I think I want to follow.
And then there's the Marketplace publishing -- need to find out how to publish both VSIXs to the same project.
Also, as you noted, I need to fix the broken build.
It's going to be a long weekend for me!

**Comment by pharring** [comment]
Also, where are you getting 17.0.2120-preview2 bits from?
I work at Microsoft, but this is my home/hobby project, so I'm not allowed to "cross the streams".

**Comment by pharring** [comment]
Thanks for the support, @kzu 
As I mentioned, it's going to require more than just those nuget updates. Besides, I don't have access to preview 2 like Mads.
I'm working through it now.

**Pull request closed without merging**
